### ISSUE TITLE
Api CI for Test and build

### ISSUE THREAD

**Issue by borjar20** [Pingu-Developers/InnosoftAPI#1]

**Comment by alesancor1** [comment]
CI can be divided in two, depending which branch commits are pushed to:

* When commits are pushed to develop:

> 1. Run lint
> 2. Run tests (mocha)
> 3. Run nyc coverage and upload to coveralls.io
> 4. Docker build
> 5. Docker push using develop tag

* When commits are pushed to main:
> 1. Run lint
> 2. Run tests (mocha)
> 3. Run nyc coverage and upload to coveralls.io
> 4. Generate a changelog based on commit messages
> 5. Create a new github release.
> 6. Create an automatic pull request for synchronizig develop and main
> 7. Docker image build
> 8. Docker push using release version tag
