### ISSUE TITLE
Mejora Calendario ordenar por horas

### ISSUE THREAD

**Issue by tomgalbar** [Pingu-Developers/InnosoftAPI#10]
Los eventos del calendario no salen ordenados por hora.

**Comment by alesancor1** [comment]
Resuelto en 01ca744.

**Comment by alesancor1** [comment]
Los test fallaban dado que no se tenía en cuenta que la fecha podía ser igual, en caso de ser iguales, se ordena por ID. Resuelto en fd471be.
